name: Run E2E Tests
description: Runs Playwright E2E tests against specified environment

inputs:
  base-url:
    description: 'Base URL to run tests against'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install Playwright browsers
      run: npx playwright install --with-deps
      shell: bash

    - name: Run Playwright tests
      run: npm run test:e2e
      env:
        BASE_URL: ${{ inputs.base-url }}
      shell: bash
