name: Deploy on push

on:
  push:
    branches:
      - master

jobs:
  deploy-vercel:
    uses: ./.github/workflows/deploy-vercel.yml
    secrets: inherit

  run-e2e-tests:
    needs: deploy-vercel
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download deploy URL
        uses: actions/download-artifact@v3
        with:
          name: deploy-url

      - name: Read deploy URL
        id: read-url
        run: echo "BASE_URL=$(cat deploy-url.txt)" >> $GITHUB_ENV

      - name: Run E2E Tests
        uses: ./.github/actions/e2e-tests
        with:
          base-url: ${{ env.BASE_URL }}
