name: Deploy on push

on:
  push:
    branches:
      - master

jobs:
  deploy-vercel:
    uses: ./.github/workflows/deploy-vercel.yml
    secrets: inherit

  run-e2e-tests:
    needs: deploy-vercel
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Debug DEPLOY_URL
        run: echo "DEPLOY_URL $DEPLOY_URL"
        shell: bash

      - name: Run E2E Tests
        uses: ./.github/actions/e2e-tests
        with:
          base-url: $DEPLOY_URL
