name: Deploy on push

on:
  push:
    branches:
      - master

jobs:
  deploy-vercel:
    uses: ./.github/workflows/deploy-vercel.yml
    secrets: inherit

  run-e2e-tests:
    needs: deploy-vercel
    uses: ./.github/actions/e2e-tests
    with:
      base-url: ${{ needs.deploy-vercel.outputs.deploy-url }}
